FROM node:18-alpine

WORKDIR /app

RUN npm install -g pnpm@9

COPY pnpm-workspace.yaml ./
COPY pnpm-lock.yaml ./
COPY package.json ./
COPY packages/ ./packages/
COPY apps/web/ ./apps/web/
COPY apps/api/ ./apps/api/

RUN pnpm install --no-frozen-lockfile

RUN pnpm --filter web build

WORKDIR /app/apps/web

EXPOSE 3000
ENV HOSTNAME=0.0.0.0

CMD ["node_modules/.bin/next", "start"]