[phases.setup]
nixPkgs = ["nodejs_18"]

[phases.install]
cmds = [
  "npm install -g pnpm@9 --prefix /usr/local",
  "export PATH=$PATH:/usr/local/bin && pnpm install --no-frozen-lockfile"
]

[phases.build]
cmds = [
  "export PATH=$PATH:/usr/local/bin && pnpm --filter api exec prisma generate",
  "export PATH=$PATH:/usr/local/bin && pnpm --filter api build"
]

[start]
cmd = "pnpm --filter api exec prisma migrate deploy && pnpm --filter api exec prisma db seed && node apps/api/dist/index.js"